### ISSUE TITLE
Handling included Javascript

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/clientkit#74]
How should we handle javascript? Want to get the mobile nav in but it needs a few lines of js. Should we just build a clientkit.js that gets included on the site or should we figure out some way to import the module from the site-side of things (not sure if we can configure require paths)?

Something else I was thinking about was having a config where we list what modules we want to be built. Might look something like:

``` yaml
modules:
  - tabs
  - navbar
  - modal
```

Not only could it cut down the CSS by not including things we don't need but it could auto build out the common.js file.

@firstandthird/developers thoughts?

**Comment by Belelros** [comment]
I agree with your thoughts @dawnerd I actually was thinking about this when working on the Flex Grid. If a project doesn't makes use of it then why should it include that CSS?

**Comment by jgallen23** [comment]
Regarding CSS, we can already do that.  The styles directory is in the path, so in the project's common.css, you can do `@import tabs.css;` and it'll grab from clientkit.  `import default.css` will import everything.

For js, since we are using babel/browserify, I think we'll just need to add `clientkit/scripts` to the import path so the projects can import the scripts they need.

The question I have is, should clientkit serve up the already babelified version or the es6 version and have the parent project's process handle it?  We have `global: true` right now, but it's slow because it will process all dependencies.
